spring:
  datasource:
    url: 'jdbc:mysql:///security_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true'
    username: root
    password: 123456

  session:
    store-type: none

  messages:
    basename: i18n.login
  thymeleaf:
    cache: false

zhipeng:
  security:
    browser:
      loginType: JSON
      signUpUrl: '/demo-signUp.html'
    social:
      qq:
        app-id: 101517573
        app-secret: ba58262e5d7441ad3ed4f9603948b880
#    code:
#      image:
#        length: 4
#        width: 100
#        urls: /user,/user/*
#      loginPage: /demo-signIn.html
#security:
#  basic:
server:
  port: 80
#    enabled: false